'use strict';
const assert = require('assert');
const { wrestlingPromotionFight, isWrestlingPromotionOpen } = require('./wrestling-promotion');
const match = { _id: '012345678901234567890123', status: 'OPEN', publicVisible: true, eventName: 'Money in the Bank', matchTitle: 'Knight vs Reigns', competitorA: { displayName: 'LA Knight', image: 'a.jpg' }, competitorB: { displayName: 'Roman Reigns', image: 'b.jpg' }, timeTba: true, eventDate: '2026-10-10', lockAt: null, entryFeeTokens: 5000, basePot: 100000, currentPot: 120000, bannerImage: 'event-poster.jpg' };
const fight = wrestlingPromotionFight(match);
assert.equal(fight.matchFighterA, 'LA Knight');
assert.equal(fight.matchFighterB, 'Roman Reigns');
assert.equal(fight.matchTokens, 5000);
assert.equal(fight.pot, 120000);
assert.equal(fight.fightPosterImage, 'event-poster.jpg');
assert.equal(fight.gameMode, 'PRO_WRESTLING');
assert.equal(fight.matchDateKey, '2026-10-10');
assert(isWrestlingPromotionOpen(fight));
assert(!isWrestlingPromotionOpen({ ...fight, status: 'DRAFT' }));
assert(!isWrestlingPromotionOpen({ ...fight, status: 'LIVE' }));
assert(!isWrestlingPromotionOpen({ ...fight, publicVisible: false }));
assert(!isWrestlingPromotionOpen({ ...fight, lockAt: new Date('2020-01-01') }));
assert.equal(wrestlingPromotionFight({ ...match, fightPosterImage: 'affiliate-poster.jpg' }).fightPosterImage, 'affiliate-poster.jpg');
console.log('Wrestling affiliate promotion tests passed');
